"""initial schema: users, api_keys, conversations, messages, requests

Phase 1, Step 2. Hand-written rather than autogenerated: autogenerate does not
emit the partial unique index that enforces "at most one system message per
conversation", and it names CHECK constraints inconsistently.

Constraint names here are the *unresolved* ones, matching ``app/db/models.py``
exactly: Alembic's operations apply the naming convention from ``target_metadata``
themselves, so ``name="role_known"`` lands in Postgres as
``ck_messages_role_known``. Passing the resolved name instead produces
``ck_messages_ck_messages_role_known`` and an autogenerate diff forever after.

``gen_random_uuid()`` is built into Postgres 13+, so no pgcrypto extension is
required on either postgres:16-alpine or Supabase.

Revision ID: 0001
Revises:
Create Date: 2026-08-10
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ----------------------------------------------------------------- users --
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), server_default=sa.text("'free'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("tier in ('free', 'plus')", name="tier_known"),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # -------------------------------------------------------------- api_keys --
    op.create_table(
        "api_keys",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("last_4", sa.Text(), nullable=False),
        sa.Column("nickname", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_api_keys_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_api_keys"),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
    )
    op.create_index("ix_api_keys_user_id", "api_keys", ["user_id"])

    # --------------------------------------------------------- conversations --
    op.create_table(
        "conversations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("preferred_slot", sa.Text(), server_default=sa.text("'auto'"), nullable=False),
        sa.Column("pinned_model", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_conversations_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_conversations"),
    )
    # The sidebar query, and the ownership-scoping key: every read filters on
    # user_id in the SQL itself.
    op.create_index(
        "ix_conversations_user_id_updated_at",
        "conversations",
        ["user_id", sa.text("updated_at DESC")],
    )

    # -------------------------------------------------------------- messages --
    op.create_table(
        "messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Contract B invariant 4 — an empty generation is an error, not a row.
        sa.CheckConstraint(
            "jsonb_typeof(content) = 'array' and jsonb_array_length(content) > 0",
            name="content_non_empty_array",
        ),
        sa.CheckConstraint("role in ('system', 'user', 'assistant')", name="role_known"),
        sa.CheckConstraint("seq >= 0", name="seq_non_negative"),
        # Invariant 1 — a system message always sits at seq 0. With the unique
        # constraint below, that already caps a conversation at one system message.
        sa.CheckConstraint("role <> 'system' or seq = 0", name="system_message_is_first"),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_messages_conversation_id_conversations",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_messages"),
        # Invariant 2, the uniqueness half. This constraint's index is also the
        # ordering index for history reads — no separate (conversation_id, seq).
        sa.UniqueConstraint("conversation_id", "seq", name="uq_messages_conversation_id_seq"),
    )
    # Redundant given the two constraints above, kept as the explicit statement of
    # "at most one system message per conversation".
    op.create_index(
        "uq_messages_one_system_per_conversation",
        "messages",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("role = 'system'"),
    )

    # -------------------------------------------------------------- requests --
    op.create_table(
        "requests",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("api_key_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("requested_slot", sa.Text(), nullable=True),
        sa.Column("served_slot", sa.Text(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("substituted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "attempts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("wasted_tokens_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Usage history outlives the key that made the call and the conversation it
        # belonged to — SET NULL, never CASCADE, on those two.
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
            name="fk_requests_api_key_id_api_keys",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_requests_conversation_id_conversations",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_requests_user_id_users", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_requests"),
    )
    op.create_index(
        "ix_requests_user_id_created_at",
        "requests",
        ["user_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "ix_requests_provider_created_at",
        "requests",
        ["provider", sa.text("created_at DESC")],
    )


def downgrade() -> None:
    # Reverse dependency order: nothing is dropped while a foreign key still
    # points at it.
    op.drop_index("ix_requests_provider_created_at", table_name="requests")
    op.drop_index("ix_requests_user_id_created_at", table_name="requests")
    op.drop_table("requests")

    op.drop_index("uq_messages_one_system_per_conversation", table_name="messages")
    op.drop_table("messages")

    op.drop_index("ix_conversations_user_id_updated_at", table_name="conversations")
    op.drop_table("conversations")

    op.drop_index("ix_api_keys_user_id", table_name="api_keys")
    op.drop_table("api_keys")

    op.drop_table("users")
