"""provider_keys, user_quota_allocations

Phase 6, Step 1. Two tables: the BYOK credential store and the personal daily
cap override that goes with it (D39). Hand-written rather than autogenerated,
for the same reason 0001 was — autogenerate does not emit the partial unique
index this migration needs.

``provider_keys`` follows ``project-overview.md`` §6's ``owner_type`` /
``owner_id`` split, but D37 keeps the shared pool in ``Settings`` rather than
in this table: only ``owner_type='user'`` rows are ever written by application
code in v1. The CHECK and the nullable ``owner_id`` are created exactly as §6
specifies so a later phase could populate the ``system`` half without a
migration, but nothing does yet. The partial unique index on
``(owner_id, provider) WHERE owner_type = 'user' AND is_active`` is §9.5's
granularity — one live key per user per provider — and is partial specifically
so a soft-deleted (``is_active = false``) row never blocks re-adding.

``user_quota_allocations`` stores the daily cap only, not a live count —
``daily_used``/``window_reset_at`` from §6 are deliberately absent; D39 records
why (the live count is Redis, and a Postgres row racing the hot path against a
Lua script is the exact naive counting ``quota/tracker.py``'s own docstring
argues against).

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-24
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --------------------------------------------------------- provider_keys --
    op.create_table(
        "provider_keys",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("owner_type", sa.Text(), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("encrypted_key", sa.Text(), nullable=False),
        sa.Column("last_4", sa.Text(), nullable=False),
        sa.Column("nickname", sa.Text(), nullable=True),
        sa.Column(
            "validation_status",
            sa.Text(),
            server_default=sa.text("'unverified'"),
            nullable=False,
        ),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("owner_type in ('system', 'user')", name="owner_type_known"),
        sa.CheckConstraint(
            "(owner_type = 'system' and owner_id is null) "
            "or (owner_type = 'user' and owner_id is not null)",
            name="owner_type_matches_owner_id",
        ),
        sa.CheckConstraint(
            "validation_status in ('valid', 'invalid', 'unverified')",
            name="validation_status_known",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name="fk_provider_keys_owner_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_keys"),
    )
    op.create_index(
        "ix_provider_keys_owner_id_provider", "provider_keys", ["owner_id", "provider"]
    )
    op.create_index(
        "uq_provider_keys_owner_id_provider_active",
        "provider_keys",
        ["owner_id", "provider"],
        unique=True,
        postgresql_where=sa.text("owner_type = 'user' and is_active"),
    )

    # ------------------------------------------------- user_quota_allocations --
    op.create_table(
        "user_quota_allocations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("daily_cap", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("daily_cap > 0", name="daily_cap_positive"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_user_quota_allocations_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_user_quota_allocations"),
        sa.UniqueConstraint(
            "user_id",
            "provider",
            "model",
            name="uq_user_quota_allocations_user_id_provider_model",
        ),
    )


def downgrade() -> None:
    op.drop_table("user_quota_allocations")

    op.drop_index("uq_provider_keys_owner_id_provider_active", table_name="provider_keys")
    op.drop_index("ix_provider_keys_owner_id_provider", table_name="provider_keys")
    op.drop_table("provider_keys")
