/**
 * The `ModelIndicator`'s input shape, and the adapters that produce it.
 *
 * This module exists so that the component has exactly **one** prop shape while
 * the same facts arrive from three different places:
 *
 *   - a stored message's `meta`            → `fromMessageMeta`   (Phase 1)
 *   - a fresh completion response          → `fromCompletion`    (Phase 1)
 *   - a stream's `done` event              → `fromDoneEvent`     (Phase 2)
 *
 * The third landed in Step 11 and cost exactly what Phase 1 predicted it would:
 * one function here, and not a line in `ModelIndicator` or in any of its callers.
 * `fromMetaEvent` is the one thing the original note did not anticipate — a
 * half-written bubble still needs something under it, and `done` has not arrived
 * yet.
 *
 * §1.1 and §2.2.2 of doc/reference/contracts-and-phase1.md are the spec.
 */

import type { DoneEvent, MetaEvent, RestartEvent } from "./sse";
import type {
  ChatCompletionResponse,
  ExtractionTier,
  Message,
  MessageMeta,
  ServedBy,
} from "./types";

/** One provider attempt, for the `attempts > 1` trail. Phase 2 populates it. */
export type Attempt = {
  attempt: number;
  provider: string;
  model: string;
  slot: string;
  outcome: "failed" | "served";
  reason?: string;
};

export type Provenance = {
  /** Always present. There is no state in which the gateway declines to say who answered. */
  servedBy: ServedBy;
  /** The slot the client asked for. `null` when unrecorded on an older row. */
  requestedSlot: string | null;
  /** True only when an explicit slot choice was overridden — never for `auto`. */
  substituted: boolean;
  attempts: number;
  /** An attachment reached the model via local OCR rather than a model that can read it. */
  degraded: boolean;
  /**
   * *How* the turn's attachments reached the model (D25), or `null` when it
   * carried none. The worst tier across the turn, so one badly-read document
   * cannot hide behind three well-read ones.
   *
   * `degraded` says an answer is untrustworthy; this says why, and it says
   * something worth rendering even when the answer is fine — "read directly" and
   * "read by another model" are different guarantees, and the same disclosure
   * discipline that produced `served_by` applies to them.
   */
  extractionTier: ExtractionTier | null;
  /**
   * How many older turns D4's fitting step dropped to build this answer
   * (Phase 5, D34). `0` means the whole stored history reached the model.
   *
   * An integer rather than a boolean, deliberately: "148 earlier messages
   * omitted" and "some earlier messages were omitted" are different
   * sentences, and only one of them is worth reading.
   */
  messagesDropped: number;
  /**
   * The pin disclosure (D3/D32): set when the conversation is pinned to one
   * model and the pin overrode the slot this turn actually asked for.
   *
   * A *disclosure*, not an error — it arrives on a 200 with a real answer
   * under it, and belongs in the same visual register as the degraded notice
   * rather than in a `TurnErrorCard`.
   */
  warning: string | null;
  tokensIn: number | null;
  tokensOut: number | null;
  /** Tokens generated by an attempt whose output was discarded (D1). */
  wastedTokensOut: number;
  /** Undefined until Phase 2 records the trail; the indicator degrades to a count. */
  attemptTrail?: Attempt[];
};

/**
 * A stored assistant message's `meta` → `Provenance`.
 *
 * Returns `null` rather than a half-filled object when the row carries no
 * provider: invariant 5 says `provider_used` is non-null on every assistant
 * message, so a missing one means this is not an assistant turn (or is a row
 * written before the invariant was enforced). Either way there is nothing
 * honest to render, and rendering "unknown model" would be worse than rendering
 * nothing.
 */
export function fromMessageMeta(meta: Partial<MessageMeta> | undefined): Provenance | null {
  if (!meta || !meta.provider_used || !meta.model_used) return null;

  return {
    servedBy: {
      slot: meta.slot_used ?? "",
      provider: meta.provider_used,
      model: meta.model_used,
    },
    requestedSlot: meta.requested_slot ?? null,
    substituted: meta.substituted ?? false,
    attempts: meta.attempts ?? 1,
    degraded: meta.degraded ?? false,
    // `?? null` rather than `?? undefined`: a row written before Phase 4 has no
    // key at all, and "this turn had no attachment" is the honest reading of
    // that — it is also true.
    extractionTier: meta.extraction_tier ?? null,
    // `?? 0` for the same reason, and it is the server's own rule: a row
    // written before Phase 5 has no key, and nobody knows whether that turn
    // was truncated. Reading the default is honest; inventing a number is not.
    messagesDropped: meta.messages_dropped ?? 0,
    // Never stored. The pin warning is about *this request* — which slot it
    // asked for and what the pin did to that — and a stored row has no request
    // to disclose against. `conversations.pinned_model` is where the durable
    // half of that fact lives.
    warning: null,
    tokensIn: meta.tokens_in ?? null,
    tokensOut: meta.tokens_out ?? null,
    wastedTokensOut: meta.wasted_tokens_out ?? 0,
  };
}

/** Convenience for the common call site: an assistant message straight from history. */
export function fromMessage(message: Message): Provenance | null {
  return message.role === "assistant" ? fromMessageMeta(message.meta) : null;
}

/**
 * A fresh `POST /v1/chat/completions` response → `Provenance`.
 *
 * The field names on the response were chosen to match the `done` event
 * field-for-field, so this function and the Phase 2 one will be near-identical.
 * That is the contract working, not duplication.
 */
export function fromCompletion(response: ChatCompletionResponse): Provenance {
  return {
    servedBy: response.served_by,
    requestedSlot: response.requested_slot,
    substituted: response.substituted,
    attempts: response.attempts,
    degraded: response.degraded,
    extractionTier: response.extraction_tier ?? null,
    messagesDropped: response.messages_dropped ?? 0,
    warning: response.warning ?? null,
    tokensIn: response.usage.prompt_tokens,
    tokensOut: response.usage.completion_tokens,
    wastedTokensOut: 0,
  };
}

/**
 * A stream's `done` event → `Provenance`.
 *
 * Near-identical to `fromCompletion`, and that is the contract paying out rather
 * than duplication: `DoneEvent` was defined to be structurally the non-streaming
 * response's provenance block precisely so that a streamed answer and a stored
 * one render through the same component with the same props. A test asserts the
 * two produce an equal object from the same facts.
 *
 * The trail is passed in because `done` does not carry one — see
 * `buildAttemptTrail`.
 */
export function fromDoneEvent(done: DoneEvent, attemptTrail?: Attempt[]): Provenance {
  return {
    servedBy: done.served_by,
    requestedSlot: done.requested_slot,
    substituted: done.substituted,
    attempts: done.attempts,
    degraded: done.degraded,
    extractionTier: done.extraction_tier ?? null,
    messagesDropped: done.messages_dropped ?? 0,
    warning: done.warning ?? null,
    tokensIn: done.usage.prompt_tokens,
    tokensOut: done.usage.completion_tokens,
    // The one number `fromCompletion` can never have: tokens a discarded attempt
    // really generated and the free tier really charged for.
    wastedTokensOut: done.usage.wasted_tokens_out ?? 0,
    attemptTrail,
  };
}

/**
 * A stream's `meta` event → `Provenance`, mid-flight.
 *
 * Everything here is provisional and gets overwritten by `fromDoneEvent` the
 * moment the stream ends. It exists because the indicator sits *under* the
 * bubble while the bubble is still being written, and rendering nothing there
 * until `done` would mean the model name appears only after the answer is
 * complete — turning the disclosure into a footnote.
 *
 * `substituted` is computed rather than read: `meta` carries the two slots but
 * not the verdict. This mirrors `selection.is_substitution` server-side —
 * resolving `auto` is not a substitution, because nothing was overridden.
 */
export function fromMetaEvent(meta: MetaEvent): Provenance {
  return {
    servedBy: { slot: meta.slot, provider: meta.provider, model: meta.model },
    requestedSlot: meta.requested_slot,
    substituted: meta.requested_slot !== "auto" && meta.requested_slot !== meta.slot,
    attempts: meta.attempt,
    degraded: false,
    // Both unknown mid-stream. The lane runs *after* `meta` is emitted — that
    // is where D13's first-byte boundary put it — so a tier claimed here would
    // be a guess, and the indicator simply says nothing about perception until
    // `done` replaces this object.
    extractionTier: null,
    // Both unknown at `meta` too, and for the same reason: the event carries
    // neither, so anything here would be a guess. `0`/`null` is what the
    // indicator reads as "nothing to disclose", exactly as `degraded: false`
    // above does — and `done` replaces this whole object moments later.
    messagesDropped: 0,
    warning: null,
    // Unknown until `done`. Null rather than 0: the indicator renders a token
    // count it is given, and "0 in · 0 out" under a streaming answer is a lie.
    tokensIn: null,
    tokensOut: null,
    wastedTokensOut: 0,
  };
}

/**
 * The attempt trail, assembled from what the client watched happen.
 *
 * This is the only place the trail can come from on this side of the wire.
 * `done` carries a count and no history, and a stored `MessageMeta` carries the
 * same — the full record lives in the `requests` row, which the chat UI has no
 * endpoint for (that is Phase 7's dashboard). So the trail is built from the
 * `meta` and `restart` events actually observed during *this* stream.
 *
 * The consequence, worth knowing rather than papering over: a candidate that
 * failed before producing a single token restarts silently, so it never appears
 * here even though it counts toward `done.attempts`. The indicator falls back to
 * the count when the trail is shorter, which is why `AttemptTrail` was written to
 * degrade to a count in the first place.
 */
export function buildAttemptTrail(
  meta: MetaEvent | null,
  restarts: RestartEvent[],
  status: "ok" | "failed",
): Attempt[] {
  if (!meta) return [];

  const trail: Attempt[] = [];
  let current: Attempt = {
    attempt: meta.attempt,
    provider: meta.provider,
    model: meta.model,
    slot: meta.slot,
    outcome: "failed",
  };

  for (const restart of restarts) {
    // A restart names what died and what takes over: it closes the open attempt
    // and opens the next one.
    trail.push({ ...current, outcome: "failed", reason: restartReason(restart.reason) });
    current = {
      attempt: restart.attempt,
      provider: restart.next.provider,
      model: restart.next.model,
      slot: restart.next.slot,
      outcome: "failed",
    };
  }

  trail.push(
    status === "ok"
      ? { ...current, outcome: "served" }
      : { ...current, outcome: "failed", reason: "no providers left to try" },
  );

  return trail;
}

/**
 * A normalized error code → something a person can read.
 *
 * The codes come off `ProviderError.code`, so the map is the normalized error
 * hierarchy and nothing else — provider-specific strings die inside
 * `parse_error` and never reach a browser. An unmapped code falls through to
 * itself rather than to "unknown", the same rule `models.ts` follows.
 */
export function restartReason(code: string): string {
  return RESTART_REASONS[code] ?? code.replace(/_/g, " ");
}

const RESTART_REASONS: Record<string, string> = {
  // app/providers/errors.py, the `code` class attribute on each normalized class.
  // Only the failover-eligible ones can ever appear on a restart; the rest are
  // terminal by their own flags and end the stream instead.
  rate_limited: "rate limited",
  provider_unavailable: "provider unavailable",
  provider_auth_failed: "provider rejected our key",
  empty_response: "returned nothing usable",
};
