/**
 * The `ModelIndicator`'s input shape, and the adapters that produce it.
 *
 * This module exists so that the component has exactly **one** prop shape while
 * the same facts arrive from three different places:
 *
 *   - a stored message's `meta`            → `fromMessageMeta`   (Phase 1)
 *   - a fresh completion response          → `fromCompletion`    (Phase 1)
 *   - a stream's `done` event              → `fromDoneEvent`     (Phase 2)
 *
 * The first two ship now. The third is why the component's contract can be
 * frozen today: adding it is a function in this file, not a change to the
 * component or to any of its callers.
 *
 * §1.1 and §2.2.2 of doc/reference/contracts-and-phase1.md are the spec.
 */

import type { ChatCompletionResponse, Message, MessageMeta, ServedBy } from "./types";

/** One provider attempt, for the `attempts > 1` trail. Phase 2 populates it. */
export type Attempt = {
  attempt: number;
  provider: string;
  model: string;
  slot: string;
  outcome: "failed" | "served";
  reason?: string;
};

export type Provenance = {
  /** Always present. There is no state in which the gateway declines to say who answered. */
  servedBy: ServedBy;
  /** The slot the client asked for. `null` when unrecorded on an older row. */
  requestedSlot: string | null;
  /** True only when an explicit slot choice was overridden — never for `auto`. */
  substituted: boolean;
  attempts: number;
  /** An attachment reached the model via local OCR rather than a model that can read it. */
  degraded: boolean;
  tokensIn: number | null;
  tokensOut: number | null;
  /** Tokens generated by an attempt whose output was discarded (D1). */
  wastedTokensOut: number;
  /** Undefined until Phase 2 records the trail; the indicator degrades to a count. */
  attemptTrail?: Attempt[];
};

/**
 * A stored assistant message's `meta` → `Provenance`.
 *
 * Returns `null` rather than a half-filled object when the row carries no
 * provider: invariant 5 says `provider_used` is non-null on every assistant
 * message, so a missing one means this is not an assistant turn (or is a row
 * written before the invariant was enforced). Either way there is nothing
 * honest to render, and rendering "unknown model" would be worse than rendering
 * nothing.
 */
export function fromMessageMeta(meta: Partial<MessageMeta> | undefined): Provenance | null {
  if (!meta || !meta.provider_used || !meta.model_used) return null;

  return {
    servedBy: {
      slot: meta.slot_used ?? "",
      provider: meta.provider_used,
      model: meta.model_used,
    },
    requestedSlot: meta.requested_slot ?? null,
    substituted: meta.substituted ?? false,
    attempts: meta.attempts ?? 1,
    degraded: meta.degraded ?? false,
    tokensIn: meta.tokens_in ?? null,
    tokensOut: meta.tokens_out ?? null,
    wastedTokensOut: meta.wasted_tokens_out ?? 0,
  };
}

/** Convenience for the common call site: an assistant message straight from history. */
export function fromMessage(message: Message): Provenance | null {
  return message.role === "assistant" ? fromMessageMeta(message.meta) : null;
}

/**
 * A fresh `POST /v1/chat/completions` response → `Provenance`.
 *
 * The field names on the response were chosen to match the `done` event
 * field-for-field, so this function and the Phase 2 one will be near-identical.
 * That is the contract working, not duplication.
 */
export function fromCompletion(response: ChatCompletionResponse): Provenance {
  return {
    servedBy: response.served_by,
    requestedSlot: response.requested_slot,
    substituted: response.substituted,
    attempts: response.attempts,
    degraded: response.degraded,
    tokensIn: response.usage.prompt_tokens,
    tokensOut: response.usage.completion_tokens,
    wastedTokensOut: 0,
  };
}
